# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.python('testModuleImporterLib', ['testModuleImporterLib.cc'])
scripts.BasicSConscript.tests(noBuildList=['testModuleImporterLib.cc'],
                              pySingles=['testModuleImporter2.py'], pyList=[])
